apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lanik-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: lanik-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
